INSERT INTO PRODUCTS (USER_ID, TYPE) VALUES (1, 'DEBIT');
INSERT INTO PRODUCTS (USER_ID, TYPE) VALUES (1, 'CREDIT');

INSERT INTO TRANSACTIONS (USER_ID, PRODUCT_ID, TYPE, AMOUNT)
VALUES (1, 1, 'DEPOSIT', 5000.00);

INSERT INTO TRANSACTIONS (USER_ID, PRODUCT_ID, TYPE, AMOUNT)
VALUES (1, 1, 'SPEND', 1500.00);
