CREATE TABLE IF NOT EXISTS PRODUCTS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    TYPE VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS TRANSACTIONS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    TYPE VARCHAR(50) NOT NULL,
    AMOUNT DECIMAL(15,2) NOT NULL,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID)
);
